### PR TITLE
Add random data

### PR DESCRIPTION
**Pull request by enekomartinmartinez**
Add random data and expected values for testing random functions in PySD https://github.com/SDXorg/pysd/pull/441

### CODE REVIEW

**Review by JamesPHoughton — APPROVED** [review]
cool! these are taken from both vensim and generated from python? Might make sense to put a readme in this folder.

**Comment by enekomartinmartinez** [comment]
The `*_vensim.tab` ones are generated by Vensim, thanks to @parksehoon1971, as explained in https://github.com/SDXorg/pysd/issues/107

The `*_expected.tab` ones I generated them with Python looking to the expected values of those distributions (following Vensim's definitions).

I will add the README with acknowledgements tomorrow.

**Comment by enekomartinmartinez** [comment]
@parksehoon1971, please could you give me information about the Vensim version you are running so I can add it to the README for traceability?

**Comment by parksehoon1971** [comment]
@enekomartinmartinez 
Your addition of the function would be of great help. Thank you so much! The Vensim version I used is PLE 10.1.4. Please check the picture file for additional information. In the future, as I test the Python web app for inventory management, I may request additional development of functions that have not yet been developed. I hope you can help me then as well. I hope you are always happy. thank you!

**Pull request merged**
